postgresql:
  global:
    postgresql:
      auth:
        database: admin_db
        existingSecret: "postgres-auth-secret"
        secretKeys:
          adminPasswordKey: "postgres-password"
  primary:
    initdb:
      scriptsConfigMap: postgres-init-script

kafka:
  kraft:
    enabled: true  # Activates KRaft Mode (No ZooKeeper required)
  zookeeper:
    enabled: false # Explicitly turns off ZooKeeper
  replicaCount: 1  # Single broker cluster for local development