apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: infrastructure
data:
  init-schemas.sh: |
    #!/bin/bash
    set -e
    psql -v ON_ERROR_STOP=1 --username "postgres" --dbname "admin_db" <<-EOSQL
        CREATE DATABASE keycloak_db;
        CREATE DATABASE referential_db;
        CREATE DATABASE collection_db;
    EOSQL