apiVersion: v1
kind: Secret
metadata:
  name: postgres-auth-secret
  namespace: infrastructure
type: Opaque
stringData:
  # The keys here can be named anything, but we map them in the values.yaml
  postgres-password: "supersecretpassword"