apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: infrastructure
data:
  init-schemas.sh: |
    #!/bin/bash
    set -e
    # Prefixing with PGPASSWORD forces psql to authenticate non-interactively
    PGPASSWORD="$POSTGRES_PASSWORD" psql -v ON_ERROR_STOP=1 --username "{{ .Values.global.postgresql.auth.postgresUser }}" --dbname "{{ .Values.global.postgresql.auth.database }}" <<-EOSQL
        CREATE DATABASE keycloak_db;
        CREATE DATABASE referential_db;
        CREATE DATABASE collection_db;
    EOSQL